### ISSUE TITLE
Make nitroui components play nice with vscode and provide intellisense

### ISSUE THREAD

**Issue by yedhink** [bigbinary/nitroui#11]
We need to add proper jsdoc and the proptypes should be explicitly mentioned inorder to  provide intellisense for each of the imported components. Checking the catalog each time for knowing more about the props and related content is too much of a context switch and can easily make other devs frustrated!

Currently since we have used a lot `class` based components, converting them to functional components is not practical. Therefore let's go with the explicit definition of default proptypes and add jsdoc to augment it.

@edwinbbu Can you tell me the build process , which can be used for testing the library module in a dev env?  Is doing `yarn build` good enough?

Note that, the PR might be pretty big, since a lot of additions would come through.
@yedhink _a

**Comment by edwinbbu** [comment]
@yedhink `yarn start` can be used to start the project in development environment. You can test any component by adding in the index.js file of src folder. 

Once everything is done. Run `yarn build` to build new bundle files and increment the version number in package.js

**Comment by vinay0x** [comment]
@yedhink I would say not worry about this now. We have catalog. Let's do it only after all components are finalized and the major works are done. First we have to make sure catalog is fully done. Philson will work on that. We'll do this once all those stuff are done.

**Comment by vinay0x** [comment]
>  Checking the catalog each time for knowing more about the props and related content is too much of a context switch and can easily make other devs frustrated!

We can live with this for now. And once it's used, it gets second nature. Most props are intuitive. And complex ones can be looked up. Even very popular libraries like BlueprintJS doesn't have a complete type definition. Defering this for Q1 2021 maybe.

**Comment by vinay0x** [comment]
> @yedhink `yarn start` can be used to start the project in development environment. You can test any component by adding in the index.js file of src folder.
> 
> Once everything is done. Run `yarn build` to build new bundle files and increment the version number in package.js

Can you add build process to Readme?
