### ISSUE TITLE
[Question] About components naming - Is it PascalCase? Or some other format?

### ISSUE THREAD

**Issue by yedhink** [bigbinary/nitroui#14]
@vinay0x 

This is purely to learn what naming convention we follow for components. 

I can see that there are `Tooltip` , `Callout`, `Textarea`, `Dropdown` components and also some components like `PageLoader`, `DateInput` etc too.

So some components are fully PascalCase, whereas some are not. So a bit confused on what naming strategy we follow. Airbnb suggests to follow PascalCase. https://airbnb.io/javascript/react/#naming

Are we referring blueprintjs component naming? If yes, then `Textarea` should be changed to `TextArea` .https://blueprintjs.com/docs/#core/components/text-inputs.text-area

**Comment by vinay0x** [comment]
Components should start with a capital letter. Some words make sense when said together. Dropdown is "dropdown" and not "drop down". It's not two words. Same thing in the case of stuff like Tooltip. It's not "tool tip". You can Google "tool tip" and it'll autocorrect to "tooltip". Making these PascalCase will only confuse things more. In the case of page loader, it's two words. It's a loader for the page. It's a combination of two words so, PascalCase makes sense. Same thing with DateInput.
