### ISSUE TITLE
Alert component required 

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/nitroui#17]
In NitroHelp we are using the component `SweetAlert` which is in shared folder. 
Alert Component is required in nitroform and nitroacademy. 

cc: @vinay0x

**Comment by vinay0x** [comment]
@edwinbbu Please check how the BlockNavigation component renders the alert. I'd say let's not add extra libraries to do it. We can use Dialog or Overlay from Blueprint.

**Comment by edwinbbu** [comment]
@vinay0x  Sure. I'll create Alert using Modal component

@edwinbbu _a
