### ISSUE TITLE
[components/Modal] Minor changes required as enhancement for Modal

### ISSUE THREAD

**Issue by yedhink** [bigbinary/nitroui#6]
Changes required:-
- we need to add attribute called `submitButtonLabel`. It's currently hardcoded as "**Update"** . We should allow users to change the labels. For `cancelButton` too same idea applies. https://github.com/bigbinary/nitroui/blob/fc74852a67b3286a12e15aa3001440622daa35cc/lib/components/Modal.js#L51

- Is providing the ability to add extra buttons/utilities to footer a good idea? Or will we be making the users define their own footers from scratch, as children, if they want to modify? Currently in footer we have two buttons, with predefined layout, justfied to end and no more utilities can be added as far as I know. https://github.com/bigbinary/nitroui/blob/fc74852a67b3286a12e15aa3001440622daa35cc/lib/components/Modal.js#L41-L57

@vinay0x I can make the PR for the same, if you can confirm that these enhancements are good to go.

**Comment by vinay0x** [comment]
>we need to add attribute called submitButtonLabel

It already takes `submitButtonProps` as prop. You can pass label and it'll be overriden.
https://github.com/bigbinary/nitroui/blob/fc74852a67b3286a12e15aa3001440622daa35cc/lib/components/Modal.js#L54

> Currently in footer we have two buttons, with predefined layout, justfied to end and no more utilities can be added as far as I know.

Component libraries should handle 90% of the use cases and not 100%. If customization is needed in footer, they can always build it custom.
