### ISSUE TITLE
[components/Radio] Question on how to use this component

### ISSUE THREAD

**Issue by yedhink** [bigbinary/nitroui#7]
This is a doubt/question. I was not able to figure out, how exactly we can make use of this Radio component. https://github.com/bigbinary/nitroui/blob/master/lib/components/Radio.js

When using `blueprintjs`, we could do the following:-
```js
<RadioGroup
    label="Status"
    onChange={handle}
    selectedValue={value}
    inline
>
    <Radio label="Inactive" value={0} />
    <Radio label="WIP" value={1} />
    <Radio label="Done" value={2} />
</RadioGroup>
```

How can we do something similar using our nitroui Radio component? Can someone provide an example? I'm not sure about what exactly should be provided as children for our compoenent.

**Comment by vinay0x** [comment]
Please check [catalog](https://nitroui.netlify.app/#/)
